# Generated by Django 3.2.3 on 2021-08-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0002_preguntasrespondidas_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='puntajeObjetnido',
            new_name='puntajeObtenido',
        ),
    ]
