# Generated by Django 3.2.3 on 2021-08-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0004_auto_20210819_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='usuarioPreg',
        ),
    ]
