# Generated by Django 3.2.3 on 2021-08-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0008_alter_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='correcto',
            new_name='correcta',
        ),
    ]
