# Generated by Django 3.2.3 on 2021-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0009_rename_correcto_preguntasrespondidas_correcta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
    ]
