# Generated by Django 3.2.3 on 2021-08-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0010_alter_pregunta_max_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='usuarioPreg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='AniversarioChaco.usuario'),
        ),
    ]
