# Generated by Django 3.2.3 on 2021-08-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0017_alter_preguntasrespondidas_usuariopreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='usuarioPreg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='AniversarioChaco.usuario'),
        ),
    ]
