# Generated by Django 3.2.3 on 2021-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0018_alter_preguntasrespondidas_usuariopreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='correcta',
            field=models.BooleanField(default=False, null=True, verbose_name='Es esta la respuesta correcta?'),
        ),
    ]
