# Generated by Django 3.2.3 on 2021-08-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0019_alter_preguntasrespondidas_correcta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='Es esta la respuesta correcta?'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AniversarioChaco.elegirrespuesta'),
        ),
    ]
