# Generated by Django 3.2.3 on 2021-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0024_alter_preguntasrespondidas_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntajeTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Pungaje Total'),
        ),
    ]
