# Generated by Django 3.2.3 on 2021-08-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0025_alter_usuario_puntajetotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'preg'},
        ),
    ]
