# Generated by Django 3.2.3 on 2021-08-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0026_alter_pregunta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'pregunta'},
        ),
    ]
