# Generated by Django 3.2.3 on 2021-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0027_alter_pregunta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='Categoria',
            field=models.CharField(max_length=90, null=True, verbose_name='dificultad'),
        ),
    ]
