# Generated by Django 3.2.3 on 2021-08-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0028_pregunta_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='Categoria',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil')], max_length=90, null=True, verbose_name='dificultad'),
        ),
    ]
