# Generated by Django 3.2.3 on 2021-08-29 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0030_preguntasrespondidas_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='Categoria',
        ),
    ]
