# Generated by Django 3.2.3 on 2021-08-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0031_auto_20210828_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caract_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad_o_categoria', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dificultad_o_categoria',
            field=models.ForeignKey(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil')], null=True, on_delete=django.db.models.deletion.CASCADE, to='AniversarioChaco.caract_categoria'),
        ),
    ]
