# Generated by Django 3.2.3 on 2021-08-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0032_auto_20210829_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caract_categoria',
            name='dificultad_o_categoria',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil')], max_length=120, verbose_name='dificultad'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='dificultad_o_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AniversarioChaco.caract_categoria'),
        ),
    ]
