# Generated by Django 3.2.3 on 2021-08-29 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0034_auto_20210829_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_login',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 17, 33, 59, 113582), verbose_name='fecha de registro'),
        ),
    ]
