# Generated by Django 3.2.3 on 2021-08-29 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0035_auto_20210829_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_login',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 20, 36, 52, 125871, tzinfo=utc), verbose_name='fecha de registro'),
        ),
    ]
