# Generated by Django 3.2.3 on 2021-08-29 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0037_auto_20210829_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_login',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_modificación',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de ultima partida'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 17, 58, 29, 73619), verbose_name='fecha de login'),
        ),
    ]
