# Generated by Django 3.2.3 on 2021-08-29 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0038_auto_20210829_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_modificación',
            new_name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 18, 0, 11, 679485), verbose_name='fecha de login'),
        ),
    ]
