# Generated by Django 3.2.3 on 2021-08-30 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0040_auto_20210829_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 22, 57, 15, 364847), verbose_name='fecha de login'),
        ),
    ]
