# Generated by Django 3.2.3 on 2021-08-30 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0045_alter_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 6, 54, 53, 11559), verbose_name='fecha de login'),
        ),
    ]
