# Generated by Django 3.2.3 on 2021-08-30 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0047_auto_20210830_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 18, 33, 40, 788146), verbose_name='fecha de login'),
        ),
    ]
