# Generated by Django 3.2.3 on 2021-08-30 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0048_alter_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='CANTIDAD_PREGUNTAS_RESPONDIDAS',
        ),
        migrations.AddField(
            model_name='usuario',
            name='CANTIDAD_PREGUNTAS_RESPONDIDAS_CORRECTAMENTE',
            field=models.IntegerField(default=0, verbose_name='historial cantidad de preguntas respondidas correctamente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CANTIDAD_PARTIDAS_JUGADAS',
            field=models.IntegerField(default=0, verbose_name='historial cantidad de partidas Jugadas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 18, 46, 9, 138075), verbose_name='fecha de login'),
        ),
    ]
