# Generated by Django 3.2.3 on 2021-08-31 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0049_auto_20210830_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 1, 41, 1, 21610, tzinfo=utc), verbose_name='fecha de login'),
        ),
    ]
