# Generated by Django 3.2.3 on 2021-09-01 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0050_alter_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caract_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultad_o_categoria', models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil')], default='Facil', max_length=90, null=True, verbose_name='dificultad')),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='dificultad_o_categoria',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 2, 40, 17, 140572, tzinfo=utc), verbose_name='fecha de login'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AniversarioChaco.caract_categoria'),
        ),
    ]
