# Generated by Django 3.2.3 on 2021-09-01 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0051_auto_20210831_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caract_categoria',
            options={'verbose_name': 'dificultad'},
        ),
        migrations.AlterField(
            model_name='caract_categoria',
            name='dificultad_o_categoria',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil')], max_length=90, null=True, verbose_name='dificultad'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AniversarioChaco.caract_categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 10, 22, 54, 356809, tzinfo=utc), verbose_name='fecha de login'),
        ),
    ]
