# Generated by Django 3.2.3 on 2021-09-01 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0054_auto_20210901_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='correcta'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='texto',
            field=models.TextField(verbose_name='Texto de la respuesta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='CANTIDAD_PARTIDAS_JUGADAS',
            field=models.IntegerField(default=0, verbose_name='historial cantidad de partidas Jugadas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 20, 3, 30, 449425, tzinfo=utc), verbose_name='fecha de login'),
        ),
    ]
