# Generated by Django 3.2.3 on 2021-09-03 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0056_auto_20210903_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 21, 31, 37, 450412, tzinfo=utc), verbose_name='fecha de login'),
        ),
    ]
