# Generated by Django 3.2.3 on 2021-09-04 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AniversarioChaco', '0057_alter_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime(2021, 9, 4, 12, 4, 27, 772127, tzinfo=utc), verbose_name='fecha de login'),
        ),
    ]
